name: 'coverage'
on: # rebuild any PRs and main branch changes
  pull_request:

permissions:
  pull-requests: write

jobs:
  coverage: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          yarn install
      - run: |
          yarn build
      - run: |
          yarn test:coverage
      - uses: ./
        id: coverage
        with:
          srcBasePath: './src'
      - uses: marocchino/sticky-pull-request-comment@f6a2580ed520ae15da6076e7410b088d1c5dddd9
        with:
          message: ${{ steps.coverage.outputs.markdownReport }}