name: 'coverage'
on: # rebuild any PRs and main branch changes
  pull_request:

permissions:
  pull-requests: write

jobs:
  coverage: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@129abb77bf5884e578fcaf1f37628e41622cc371
        with:
          version: 8

      - name: Set Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm

      - run: |
          pnpm install
      - run: |
          pnpm build
      - run: |
          pnpm test:coverage
      - uses: ./
        id: coverage
        with:
          srcBasePath: './src'
      - uses: marocchino/sticky-pull-request-comment@331f8f5b4215f0445d3c07b4967662a32a2d3e31
        with:
          message: ${{ steps.coverage.outputs.markdownReport }}
      - name: Publish job summary
        run: |
          echo "## Code Coverage" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.coverage.outputs.markdownReport }}" >> $GITHUB_STEP_SUMMARY
