name: 'coverage'
on: # rebuild any PRs and main branch changes
  pull_request:

permissions:
  pull-requests: write

jobs:
  coverage: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          yarn install
      - run: |
          yarn build
      - run: |
          yarn test:coverage
      - uses: ./
        id: coverage
        with:
          srcBasePath: './src'
      - uses: marocchino/sticky-pull-request-comment@efaaab3fd41a9c3de579aba759d2552635e590fd
        with:
          message: ${{ steps.coverage.outputs.markdownReport }}
      - name: Publish job summary
        run: |
          echo "## Code Coverage" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.coverage.outputs.markdownReport }}" >> $GITHUB_STEP_SUMMARY
